import { QueryInterface, DataTypes } from 'sequelize';


export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.createTable('chatbot_messages', {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
        allowNull: false,
      },
      deal_id: {
        type: DataTypes.UUID,
        allowNull: false,
        references: {
          model: 'chatbot_deals',
          key: 'id',
        },
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE',
      },
      role: {
        type: DataTypes.ENUM('VENDOR', 'ACCORDO', 'SYSTEM'),
        allowNull: false,
        comment: 'Who sent this message',
      },
      content: {
        type: DataTypes.TEXT,
        allowNull: false,
        comment: 'Message text content',
      },
      extracted_offer: {
        type: DataTypes.JSONB,
        allowNull: true,
        comment: 'Parsed offer data from vendor message',
      },
      engine_decision: {
        type: DataTypes.JSONB,
        allowNull: true,
        comment: 'Full decision engine output',
      },
      decision_action: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'Decision: accept, counter, reject, escalate',
      },
      utility_score: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: true,
        comment: 'Utility score of the offer in this message (0-100)',
      },
      counter_offer: {
        type: DataTypes.JSONB,
        allowNull: true,
        comment: 'Counter-offer generated by Accordo',
      },
      explainability_json: {
        type: DataTypes.JSONB,
        allowNull: true,
        comment: 'Audit trail and reasoning for decision',
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.literal('CURRENT_TIMESTAMP'),
      },
    });

    // Add indexes for common queries
    await queryInterface.addIndex('chatbot_messages', ['deal_id']);
    await queryInterface.addIndex('chatbot_messages', ['role']);
    await queryInterface.addIndex('chatbot_messages', ['created_at']);
    await queryInterface.addIndex('chatbot_messages', ['deal_id', 'created_at']);
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.dropTable('chatbot_messages');
  },
};
