/**
 * Build Negotiation Intent
 *
 * Translates the deterministic engine Decision into a NegotiationIntent object.
 * This is the hard boundary between the commercial engine and the LLM renderer.
 *
 * The LLM ONLY ever sees the NegotiationIntent — never utility scores, weights,
 * thresholds, configs, or pricing formulas.
 *
 * Rules:
 * - ACCEPT:    No pricing fields exposed.
 * - COUNTER:   allowedPrice must be within [targetPrice, maxAcceptablePrice].
 * - WALK_AWAY: No pricing fields exposed.
 * - ESCALATE:  No pricing fields exposed.
 * - MESO:      offerVariants passed through unchanged from engine.
 *
 * Zero external dependencies.
 */

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type NegotiationAction = 'ACCEPT' | 'COUNTER' | 'ESCALATE' | 'WALK_AWAY' | 'MESO' | 'ASK_CLARIFY';

export type VendorTone = 'formal' | 'casual' | 'urgent' | 'firm' | 'friendly';

export interface MesoOfferVariant {
  label: string;
  price: number;
  paymentTerms: string;
  description: string;
}

/**
 * The ONLY object the LLM renderer ever receives from the commercial engine.
 * Every field is safe to expose to the LLM — no scores, no weights, no formulas.
 */
export interface NegotiationIntent {
  /** What action the engine decided */
  action: NegotiationAction;

  /**
   * Firmness level derived from utility gap (0 = soft, 1 = hard).
   * Tells the LLM how assertive to sound.
   * Utility ≥70% → 0.25 | 50–70% → 0.55 | 30–50% → 0.75 | <30% → 0.90
   */
  firmness: number;

  /**
   * A fixed, pre-written phrase describing the commercial position.
   * Selected deterministically — never generated by the LLM.
   */
  commercialPosition: string;

  /**
   * The ONLY price the LLM is allowed to mention in a COUNTER response.
   * Always within [targetPrice, maxAcceptablePrice].
   * Absent for ACCEPT, WALK_AWAY, ESCALATE.
   */
  allowedPrice?: number;

  /**
   * Payment terms for COUNTER responses (e.g. "Net 60").
   * Absent for non-COUNTER actions.
   */
  allowedPaymentTerms?: string;

  /**
   * Delivery information for COUNTER responses.
   * Absent for non-COUNTER actions.
   */
  allowedDelivery?: string;

  /**
   * The primary parameter with the lowest utility score for COUNTER responses.
   * Only 'price', 'terms', or 'delivery' — NEVER 'warranty' or 'quality'.
   * Used to help the LLM address the weakest negotiation dimension naturally.
   * Absent for non-COUNTER actions or when primary params are all strong.
   */
  weakestPrimaryParameter?: 'price' | 'terms' | 'delivery';

  /**
   * MESO offer variants, passed through unchanged from the engine.
   * The LLM may only present these — never modify or invent them.
   */
  offerVariants?: MesoOfferVariant[];

  /** Vendor concerns to acknowledge (e.g. supply chain, timeline) */
  acknowledgeConcerns: string[];

  /** Detected vendor tone — drives phrasing style in the LLM response */
  vendorTone: VendorTone;
}

// ─────────────────────────────────────────────
// Fixed Commercial Position Templates
// Selected by action + firmness — NO AI generation
// ─────────────────────────────────────────────

const COMMERCIAL_POSITIONS: Record<NegotiationAction, Record<string, string>> = {
  ACCEPT: {
    default: 'We are pleased to accept this offer as it meets our procurement requirements.',
    friendly: 'This offer works well for us and we are happy to proceed.',
    formal: 'We confirm formal acceptance of the terms as presented.',
  },
  COUNTER: {
    high_firmness:   'Our budget constraints require us to maintain firm terms for this procurement.',
    medium_firmness: 'We are working toward mutually beneficial terms that align with our requirements.',
    low_firmness:    'We remain flexible and are committed to finding an arrangement that works for both parties.',
    urgent:          'Given our project timeline, we need to reach an agreement on these terms promptly.',
  },
  WALK_AWAY: {
    default: 'After careful consideration, the current terms do not align with our procurement requirements.',
    firm:    'We have reached the limit of what is workable within our constraints.',
  },
  ESCALATE: {
    default: 'This negotiation requires senior review before we can proceed further.',
  },
  MESO: {
    default: 'We have prepared several options that may work for both parties.',
  },
  ASK_CLARIFY: {
    default: 'We need a few more details to move this negotiation forward.',
  },
};

/**
 * Select a commercial position phrase deterministically.
 * No LLM involved — purely a lookup.
 */
function selectCommercialPosition(
  action: NegotiationAction,
  firmness: number,
  tone: VendorTone
): string {
  const pool = COMMERCIAL_POSITIONS[action];

  if (action === 'COUNTER') {
    if (firmness >= 0.75) return pool['high_firmness'];
    if (firmness >= 0.55) return pool['medium_firmness'];
    if (tone === 'urgent') return pool['urgent'];
    return pool['low_firmness'];
  }

  if (action === 'ACCEPT') {
    if (tone === 'friendly') return pool['friendly'];
    if (tone === 'formal') return pool['formal'];
    return pool['default'];
  }

  if (action === 'WALK_AWAY') {
    if (tone === 'firm') return pool['firm'];
    return pool['default'];
  }

  return pool['default'] ?? 'We are working toward a mutually beneficial agreement.';
}

// ─────────────────────────────────────────────
// Firmness mapping from utility score
// ─────────────────────────────────────────────

/**
 * Map a utility score (0–1) to a firmness value (0–1).
 * Higher firmness = more assertive LLM tone.
 *
 * Utility ≥ 70%  → firmness 0.25  (near acceptance, stay soft)
 * Utility 50–70% → firmness 0.55  (negotiating zone, moderate)
 * Utility 30–50% → firmness 0.75  (escalation zone, firm)
 * Utility < 30%  → firmness 0.90  (walk-away zone, very firm)
 */
export function mapUtilityToFirmness(utilityScore: number): number {
  if (utilityScore >= 0.70) return 0.25;
  if (utilityScore >= 0.50) return 0.55;
  if (utilityScore >= 0.30) return 0.75;
  return 0.90;
}

// ─────────────────────────────────────────────
// Price boundary guard
// ─────────────────────────────────────────────

/**
 * Ensures allowedPrice stays within [targetPrice, maxAcceptablePrice].
 * If counterPrice is outside bounds, clamp it.
 * Returns undefined if bounds are not available (safe fallback).
 */
function resolveAllowedPrice(
  counterPrice: number | null | undefined,
  targetPrice?: number,
  maxAcceptablePrice?: number
): number | undefined {
  if (counterPrice == null) return undefined;
  if (targetPrice == null || maxAcceptablePrice == null) return counterPrice;

  const min = Math.min(targetPrice, maxAcceptablePrice);
  const max = Math.max(targetPrice, maxAcceptablePrice);

  // Clamp within valid range
  return Math.min(max, Math.max(min, counterPrice));
}

// ─────────────────────────────────────────────
// Main builder function
// ─────────────────────────────────────────────

export interface BuildIntentInput {
  /** Decision action from the engine */
  action: 'ACCEPT' | 'COUNTER' | 'ESCALATE' | 'WALK_AWAY' | 'ASK_CLARIFY';
  /** Raw utility score from the engine (0–1) */
  utilityScore: number;
  /** Counter-offer price from the engine (only used for COUNTER) */
  counterPrice?: number | null;
  /** Counter-offer payment terms from the engine (only used for COUNTER) */
  counterPaymentTerms?: string | null;
  /** Counter-offer delivery info from the engine (only used for COUNTER) */
  counterDelivery?: string | null;
  /** Vendor concerns detected in conversation */
  concerns: string[];
  /** Detected vendor tone */
  tone: VendorTone;
  /** MESO offer variants from the engine (only used for MESO action) */
  mesoOffers?: MesoOfferVariant[];
  /** PM's target price — used to validate allowedPrice boundary */
  targetPrice?: number;
  /** PM's maximum acceptable price — used to validate allowedPrice boundary */
  maxAcceptablePrice?: number;
  /**
   * The primary negotiation parameter with the lowest utility, for COUNTER responses only.
   * Only 'price', 'terms', or 'delivery' — warranty/quality are NEVER surfaced to vendor.
   * Computed in conversationService from parameterUtilities before calling buildNegotiationIntent.
   */
  weakestPrimaryParameter?: 'price' | 'terms' | 'delivery';
}

/**
 * Build a NegotiationIntent from an engine Decision.
 *
 * This is the only bridge between the commercial engine and the LLM.
 * All commercial intelligence is distilled into safe, presentation-ready fields.
 */
export function buildNegotiationIntent(input: BuildIntentInput): NegotiationIntent {
  const {
    action,
    utilityScore,
    counterPrice,
    counterPaymentTerms,
    counterDelivery,
    concerns,
    tone,
    mesoOffers,
    targetPrice,
    maxAcceptablePrice,
    weakestPrimaryParameter,
  } = input;

  // Determine if this is a MESO action (overrides base action when variants present)
  const finalAction: NegotiationAction =
    mesoOffers && mesoOffers.length > 0 ? 'MESO' : action;

  const firmness = mapUtilityToFirmness(utilityScore);
  const commercialPosition = selectCommercialPosition(finalAction, firmness, tone);

  const intent: NegotiationIntent = {
    action: finalAction,
    firmness,
    commercialPosition,
    acknowledgeConcerns: concerns,
    vendorTone: tone,
  };

  // Only COUNTER gets pricing fields and weakest parameter signal
  if (finalAction === 'COUNTER' && counterPrice != null) {
    intent.allowedPrice = resolveAllowedPrice(counterPrice, targetPrice, maxAcceptablePrice);
    if (counterPaymentTerms) {
      intent.allowedPaymentTerms = counterPaymentTerms;
    }
    if (counterDelivery) {
      intent.allowedDelivery = counterDelivery;
    }
    // Pass weakest primary parameter only for COUNTER — helps LLM focus the response.
    // Only 'price', 'terms', 'delivery' can appear here — warranty/quality are never surfaced.
    if (weakestPrimaryParameter) {
      intent.weakestPrimaryParameter = weakestPrimaryParameter;
    }
  }

  // MESO passes offer variants through unchanged
  if (finalAction === 'MESO' && mesoOffers) {
    intent.offerVariants = mesoOffers;
  }

  // ACCEPT, WALK_AWAY, ESCALATE, ASK_CLARIFY: no pricing fields

  return intent;
}
